### ISSUE TITLE
Vue package version mismatch

### ISSUE THREAD

**Issue by 1gn0r4nd** [azat-io/vuepress-plugin-umami-analytics#2]
I get the following when performing:
```
yarn add vuepress-plugin-umami-analytics
yarn dev
```

```C:\Users\User\WebstormProjects\buildonkilt\docs\node_modules\vue-server-renderer\index.js:8
  throw new Error(
  ^

Error:

Vue packages version mismatch:

- vue@3.3.10
- vue-server-renderer@2.7.15

This may cause things to work incorrectly. Make sure to use the same version for both.

    at Object.<anonymous> (C:\Users\User\WebstormProjects\buildonkilt\docs\node_modules\vue-server-renderer\index.js:8:9)
    at Module._compile (node:internal/modules/cjs/loader:1256:14)
    at Module._extensions..js (node:internal/modules/cjs/loader:1310:10)
    at Module.load (node:internal/modules/cjs/loader:1119:32)
    at Module._load (node:internal/modules/cjs/loader:960:12)
    at Module.require (node:internal/modules/cjs/loader:1143:19)
    at require (node:internal/modules/cjs/helpers:110:18)
    at Object.<anonymous> (C:\Users\User\WebstormProjects\buildonkilt\docs\node_modules\@vuepress\core\lib\node\build\index.js:11:34)
    at Module._compile (node:internal/modules/cjs/loader:1256:14)
    at Module._extensions..js (node:internal/modules/cjs/loader:1310:10)
    at Module.load (node:internal/modules/cjs/loader:1119:32)
    at Module._load (node:internal/modules/cjs/loader:960:12)
    at Module.require (node:internal/modules/cjs/loader:1143:19)
    at require (node:internal/modules/cjs/helpers:110:18)
    at Object.<anonymous> (C:\Users\User\WebstormProjects\buildonkilt\docs\node_modules\@vuepress\core\lib\node\App.js:21:22)
    at Module._compile (node:internal/modules/cjs/loader:1256:14)

Node.js v18.17.0
error Command failed with exit code 1.
info Visit https://yarnpkg.com/en/docs/cli/run for documentation about this command.```

**Comment by azat-io** [comment]
I'm not sure if it's a plugin issue. Can you create a small example to reproduce the problem?

**Comment by 1gn0r4nd** [comment]
I seem to have found the problem. I was trying to use it with Vuepress 1.xx.
